#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DSoft.Flyout.Droid.Resource", IsApplication=true)]

namespace DSoft.Flyout.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::DSoft.UI.Flyout.Resource.Attribute.moremenu_background = global::DSoft.Flyout.Droid.Resource.Attribute.moremenu_background;
			global::DSoft.UI.Flyout.Resource.Drawable.menu = global::DSoft.Flyout.Droid.Resource.Drawable.menu;
			global::DSoft.UI.Flyout.Resource.Id.FlyOutContainer = global::DSoft.Flyout.Droid.Resource.Id.FlyOutContainer;
			global::DSoft.UI.Flyout.Resource.Id.FlyOutContent = global::DSoft.Flyout.Droid.Resource.Id.FlyOutContent;
			global::DSoft.UI.Flyout.Resource.Id.FlyOutMenu = global::DSoft.Flyout.Droid.Resource.Id.FlyOutMenu;
			global::DSoft.UI.Flyout.Resource.Id.fragmentContainer = global::DSoft.Flyout.Droid.Resource.Id.fragmentContainer;
			global::DSoft.UI.Flyout.Resource.Id.menuFragmentContainer = global::DSoft.Flyout.Droid.Resource.Id.menuFragmentContainer;
			global::DSoft.UI.Flyout.Resource.Id.menuText = global::DSoft.Flyout.Droid.Resource.Id.menuText;
			global::DSoft.UI.Flyout.Resource.Id.navBar = global::DSoft.Flyout.Droid.Resource.Id.navBar;
			global::DSoft.UI.Flyout.Resource.Layout.flyout_content_layout = global::DSoft.Flyout.Droid.Resource.Layout.flyout_content_layout;
			global::DSoft.UI.Flyout.Resource.Layout.flyout_layout = global::DSoft.Flyout.Droid.Resource.Layout.flyout_layout;
			global::DSoft.UI.Flyout.Resource.Layout.flyout_menu_layout = global::DSoft.Flyout.Droid.Resource.Layout.flyout_menu_layout;
			global::DSoft.UI.Flyout.Resource.Layout.morelist_layout = global::DSoft.Flyout.Droid.Resource.Layout.morelist_layout;
			global::DSoft.UI.Flyout.Resource.Layout.moremenu_item = global::DSoft.Flyout.Droid.Resource.Layout.moremenu_item;
			global::DSoft.UI.Flyout.Resource.Layout.moremenu_segment = global::DSoft.Flyout.Droid.Resource.Layout.moremenu_segment;
			global::DSoft.UI.Flyout.Resource.String.library_name = global::DSoft.Flyout.Droid.Resource.String.library_name;
			global::DSoft.UI.Flyout.Resource.Styleable.DSFlyoutMenuFragment = global::DSoft.Flyout.Droid.Resource.Styleable.DSFlyoutMenuFragment;
			global::DSoft.UI.Flyout.Resource.Styleable.DSFlyoutMenuFragment_moremenu_background = global::DSoft.Flyout.Droid.Resource.Styleable.DSFlyoutMenuFragment_moremenu_background;
			global::DSoft.UI.Resource.String.library_name = global::DSoft.Flyout.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int moremenu_background = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int menu = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int FlyOutContainer = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int FlyOutContent = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int FlyOutMenu = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int app_layout = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int fragmentContainer = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int menuFragmentContainer = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int menuText = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int navBar = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int scene_layout = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int scene_scroller = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int txtExample = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int example_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int flyout_content_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int flyout_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int flyout_menu_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int morelist_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int moremenu_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int moremenu_segment = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] DSFlyoutMenuFragment = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int DSFlyoutMenuFragment_moremenu_background = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
