<?xml version="1.0" encoding="UTF-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-ios</TargetFramework>
		<IPhoneResourcePrefix>Resources</IPhoneResourcePrefix>
		<RootNamespace>DSoft.UI</RootNamespace>
		<AssemblyName>DSoft.UI</AssemblyName>
		<PackageId>DSoft.DSGrid</PackageId>
		<Version>3.2.0</Version>
		<AssemblyVersion>3.2.0</AssemblyVersion>
		<FileVersion>3.2.0</FileVersion>
		<Summary>A lightweight and simple-to-use xamarin data grid for iPhone and iPad</Summary>
		<Title>DSoft.DSGrid</Title>
		<Description>A lightweight and simple-to-use xamarin data grid for iPhone and iPad</Description>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\DSoft.Datatypes.Grid\DSoft.Datatypes.Grid.csproj" />
		<ProjectReference Include="..\DSoft.Datatypes\DSoft.Datatypes.csproj" />
		<ProjectReference Include="..\DSoft.Themes\DSoft.Themes.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="..\readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>